'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization

<Assembly: EdmSchemaAttribute()>
#Region "EDM Relationship Metadata"

<Assembly: EdmRelationshipAttribute("NorthwindModel", "FK_Orders_Customers", "Customers", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Entities.Customers), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Entities.Orders))>

#End Region

Namespace Entities
	#Region "Contexts"

	''' <summary>
	''' No Metadata Documentation available.
	''' </summary>
	Partial Public Class NorthwindEntities
		Inherits ObjectContext

		#Region "Constructors"

		''' <summary>
		''' Initializes a new NorthwindEntities object using the connection string found in the 'NorthwindEntities' section of the application configuration file.
		''' </summary>
		Public Sub New()
			MyBase.New("name=NorthwindEntities", "NorthwindEntities")
			OnContextCreated()
		End Sub

		''' <summary>
		''' Initialize a new NorthwindEntities object.
		''' </summary>
		Public Sub New(ByVal connectionString As String)
			MyBase.New(connectionString, "NorthwindEntities")
			OnContextCreated()
		End Sub

		''' <summary>
		''' Initialize a new NorthwindEntities object.
		''' </summary>
'INSTANT VB NOTE: The variable connection was renamed since Visual Basic does not handle local variables named the same as class members well:
		Public Sub New(ByVal connection_Conflict As EntityConnection)
			MyBase.New(connection_Conflict, "NorthwindEntities")
			OnContextCreated()
		End Sub

		#End Region

		#Region "Partial Methods"

		Partial Private Sub OnContextCreated()
		End Sub

		#End Region

		#Region "ObjectSet Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		Public ReadOnly Property Customers() As ObjectSet(Of Customers)
			Get
				If (_Customers Is Nothing) Then
					_Customers = MyBase.CreateObjectSet(Of Customers)("Customers")
				End If
				Return _Customers
			End Get
		End Property
		Private _Customers As ObjectSet(Of Customers)

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		Public ReadOnly Property Orders() As ObjectSet(Of Orders)
			Get
				If (_Orders Is Nothing) Then
					_Orders = MyBase.CreateObjectSet(Of Orders)("Orders")
				End If
				Return _Orders
			End Get
		End Property
		Private _Orders As ObjectSet(Of Orders)

		#End Region

		#Region "AddTo Methods"

		''' <summary>
		''' Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
		''' </summary>
'INSTANT VB NOTE: The parameter customers was renamed since it may cause conflicts with calls to static members of the user-defined type with this name:
		Public Sub AddToCustomers(ByVal customers_Conflict As Customers)
			MyBase.AddObject("Customers", customers_Conflict)
		End Sub

		''' <summary>
		''' Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
		''' </summary>
'INSTANT VB NOTE: The parameter orders was renamed since it may cause conflicts with calls to static members of the user-defined type with this name:
		Public Sub AddToOrders(ByVal orders_Conflict As Orders)
			MyBase.AddObject("Orders", orders_Conflict)
		End Sub

		#End Region

	End Class

	#End Region

	#Region "Entities"

	''' <summary>
	''' No Metadata Documentation available.
	''' </summary>
	<EdmEntityTypeAttribute(NamespaceName:="NorthwindModel", Name:="Customers")>
	<Serializable()>
	<DataContractAttribute(IsReference:=True)>
	Partial Public Class Customers
		Inherits EntityObject

		#Region "Factory Method"

		''' <summary>
		''' Create a new Customers object.
		''' </summary>
		''' <param name="companyName_Conflict">Initial value of the CompanyName property.</param>
		''' <param name="customerID_Conflict">Initial value of the CustomerID property.</param>
'INSTANT VB NOTE: The variable companyName was renamed since Visual Basic does not handle local variables named the same as class members well:
'INSTANT VB NOTE: The variable customerID was renamed since Visual Basic does not handle local variables named the same as class members well:
		Public Shared Function CreateCustomers(ByVal companyName_Conflict As Global.System.String, ByVal customerID_Conflict As Global.System.String) As Customers
'INSTANT VB NOTE: The variable customers was renamed since it may cause conflicts with calls to static members of the user-defined type with this name:
			Dim customers_Conflict As New Customers()
			customers_Conflict.CompanyName = companyName_Conflict
			customers_Conflict.CustomerID = customerID_Conflict
			Return customers_Conflict
		End Function

		#End Region

		#Region "Primitive Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
		<DataMemberAttribute()>
		Public Property Address() As Global.System.String
			Get
				Return _Address
			End Get
			Set(ByVal value As System.String)
				OnAddressChanging(value)
				ReportPropertyChanging("Address")
				_Address = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Address")
				OnAddressChanged()
			End Set
		End Property
		Private _Address As Global.System.String
		Partial Private Sub OnAddressChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnAddressChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
		<DataMemberAttribute()>
		Public Property City() As Global.System.String
			Get
				Return _City
			End Get
			Set(ByVal value As System.String)
				OnCityChanging(value)
				ReportPropertyChanging("City")
				_City = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("City")
				OnCityChanged()
			End Set
		End Property
		Private _City As Global.System.String
		Partial Private Sub OnCityChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnCityChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
		<DataMemberAttribute()>
		Public Property CompanyName() As Global.System.String
			Get
				Return _CompanyName
			End Get
			Set(ByVal value As System.String)
				OnCompanyNameChanging(value)
				ReportPropertyChanging("CompanyName")
				_CompanyName = StructuralObject.SetValidValue(value, False)
				ReportPropertyChanged("CompanyName")
				OnCompanyNameChanged()
			End Set
		End Property
		Private _CompanyName As Global.System.String
		Partial Private Sub OnCompanyNameChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnCompanyNameChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
		<DataMemberAttribute()>
		Public Property ContactName() As Global.System.String
			Get
				Return _ContactName
			End Get
			Set(ByVal value As System.String)
				OnContactNameChanging(value)
				ReportPropertyChanging("ContactName")
				_ContactName = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("ContactName")
				OnContactNameChanged()
			End Set
		End Property
		Private _ContactName As Global.System.String
		Partial Private Sub OnContactNameChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnContactNameChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
		<DataMemberAttribute()>
		Public Property ContactTitle() As Global.System.String
			Get
				Return _ContactTitle
			End Get
			Set(ByVal value As System.String)
				OnContactTitleChanging(value)
				ReportPropertyChanging("ContactTitle")
				_ContactTitle = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("ContactTitle")
				OnContactTitleChanged()
			End Set
		End Property
		Private _ContactTitle As Global.System.String
		Partial Private Sub OnContactTitleChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnContactTitleChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
		<DataMemberAttribute()>
		Public Property Country() As Global.System.String
			Get
				Return _Country
			End Get
			Set(ByVal value As System.String)
				OnCountryChanging(value)
				ReportPropertyChanging("Country")
				_Country = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Country")
				OnCountryChanged()
			End Set
		End Property
		Private _Country As Global.System.String
		Partial Private Sub OnCountryChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnCountryChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
		<DataMemberAttribute()>
		Public Property CustomerID() As Global.System.String
			Get
				Return _CustomerID
			End Get
			Set(ByVal value As System.String)
				If _CustomerID <> value Then
					OnCustomerIDChanging(value)
					ReportPropertyChanging("CustomerID")
					_CustomerID = StructuralObject.SetValidValue(value, False)
					ReportPropertyChanged("CustomerID")
					OnCustomerIDChanged()
				End If
			End Set
		End Property
		Private _CustomerID As Global.System.String
		Partial Private Sub OnCustomerIDChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnCustomerIDChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
		<DataMemberAttribute()>
		Public Property Fax() As Global.System.String
			Get
				Return _Fax
			End Get
			Set(ByVal value As System.String)
				OnFaxChanging(value)
				ReportPropertyChanging("Fax")
				_Fax = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Fax")
				OnFaxChanged()
			End Set
		End Property
		Private _Fax As Global.System.String
		Partial Private Sub OnFaxChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnFaxChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
		<DataMemberAttribute()>
		Public Property Phone() As Global.System.String
			Get
				Return _Phone
			End Get
			Set(ByVal value As System.String)
				OnPhoneChanging(value)
				ReportPropertyChanging("Phone")
				_Phone = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Phone")
				OnPhoneChanged()
			End Set
		End Property
		Private _Phone As Global.System.String
		Partial Private Sub OnPhoneChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnPhoneChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
		<DataMemberAttribute()>
		Public Property PostalCode() As Global.System.String
			Get
				Return _PostalCode
			End Get
			Set(ByVal value As System.String)
				OnPostalCodeChanging(value)
				ReportPropertyChanging("PostalCode")
				_PostalCode = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("PostalCode")
				OnPostalCodeChanged()
			End Set
		End Property
		Private _PostalCode As Global.System.String
		Partial Private Sub OnPostalCodeChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnPostalCodeChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
		<DataMemberAttribute()>
		Public Property Region() As Global.System.String
			Get
				Return _Region
			End Get
			Set(ByVal value As System.String)
				OnRegionChanging(value)
				ReportPropertyChanging("Region")
				_Region = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Region")
				OnRegionChanged()
			End Set
		End Property
		Private _Region As Global.System.String
		Partial Private Sub OnRegionChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnRegionChanged()
		End Sub

		#End Region


		#Region "Navigation Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<XmlIgnoreAttribute()>
		<SoapIgnoreAttribute()>
		<DataMemberAttribute()>
		<EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "FK_Orders_Customers", "Orders")>
		Public Property Orders() As EntityCollection(Of Orders)
			Get
				Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Orders)("NorthwindModel.FK_Orders_Customers", "Orders")
			End Get
			Set(ByVal value As EntityCollection(Of Orders))
				If (value IsNot Nothing) Then
					CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Orders)("NorthwindModel.FK_Orders_Customers", "Orders", value)
				End If
			End Set
		End Property

		#End Region

	End Class

	''' <summary>
	''' No Metadata Documentation available.
	''' </summary>
	<EdmEntityTypeAttribute(NamespaceName:="NorthwindModel", Name:="Orders")>
	<Serializable()>
	<DataContractAttribute(IsReference:=True)>
	Partial Public Class Orders
		Inherits EntityObject

		#Region "Factory Method"

		''' <summary>
		''' Create a new Orders object.
		''' </summary>
		''' <param name="orderID_Conflict">Initial value of the OrderID property.</param>
'INSTANT VB NOTE: The variable orderID was renamed since Visual Basic does not handle local variables named the same as class members well:
		Public Shared Function CreateOrders(ByVal orderID_Conflict As Global.System.Int32) As Orders
'INSTANT VB NOTE: The variable orders was renamed since it may cause conflicts with calls to static members of the user-defined type with this name:
			Dim orders_Conflict As New Orders()
			orders_Conflict.OrderID = orderID_Conflict
			Return orders_Conflict
		End Function

		#End Region

		#Region "Primitive Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
		<DataMemberAttribute()>
		Public Property EmployeeID() As Global.System.Int32?
			Get
				Return _EmployeeID
			End Get
			Set(ByVal value? As System.Int32)
				OnEmployeeIDChanging(value)
				ReportPropertyChanging("EmployeeID")
				_EmployeeID = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("EmployeeID")
				OnEmployeeIDChanged()
			End Set
		End Property
		Private _EmployeeID? As Global.System.Int32
		Partial Private Sub OnEmployeeIDChanging(ByVal value? As Global.System.Int32)
		End Sub
		Partial Private Sub OnEmployeeIDChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
		<DataMemberAttribute()>
		Public Property Freight() As Global.System.Decimal?
			Get
				Return _Freight
			End Get
			Set(ByVal value? As System.Decimal)
				OnFreightChanging(value)
				ReportPropertyChanging("Freight")
				_Freight = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("Freight")
				OnFreightChanged()
			End Set
		End Property
		Private _Freight? As Global.System.Decimal
		Partial Private Sub OnFreightChanging(ByVal value? As Global.System.Decimal)
		End Sub
		Partial Private Sub OnFreightChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
		<DataMemberAttribute()>
		Public Property OrderDate() As Global.System.DateTime?
			Get
				Return _OrderDate
			End Get
			Set(ByVal value? As DateTime)
				OnOrderDateChanging(value)
				ReportPropertyChanging("OrderDate")
				_OrderDate = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("OrderDate")
				OnOrderDateChanged()
			End Set
		End Property
		Private _OrderDate? As Global.System.DateTime
		Partial Private Sub OnOrderDateChanging(ByVal value? As Global.System.DateTime)
		End Sub
		Partial Private Sub OnOrderDateChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
		<DataMemberAttribute()>
		Public Property OrderID() As Global.System.Int32
			Get
				Return _OrderID
			End Get
			Set(ByVal value As System.Int32)
				If _OrderID <> value Then
					OnOrderIDChanging(value)
					ReportPropertyChanging("OrderID")
					_OrderID = StructuralObject.SetValidValue(value)
					ReportPropertyChanged("OrderID")
					OnOrderIDChanged()
				End If
			End Set
		End Property
		Private _OrderID As Global.System.Int32
		Partial Private Sub OnOrderIDChanging(ByVal value As Global.System.Int32)
		End Sub
		Partial Private Sub OnOrderIDChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
		<DataMemberAttribute()>
		Public Property RequiredDate() As Global.System.DateTime?
			Get
				Return _RequiredDate
			End Get
			Set(ByVal value? As DateTime)
				OnRequiredDateChanging(value)
				ReportPropertyChanging("RequiredDate")
				_RequiredDate = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("RequiredDate")
				OnRequiredDateChanged()
			End Set
		End Property
		Private _RequiredDate? As Global.System.DateTime
		Partial Private Sub OnRequiredDateChanging(ByVal value? As Global.System.DateTime)
		End Sub
		Partial Private Sub OnRequiredDateChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
		<DataMemberAttribute()>
		Public Property ShipAddress() As Global.System.String
			Get
				Return _ShipAddress
			End Get
			Set(ByVal value As System.String)
				OnShipAddressChanging(value)
				ReportPropertyChanging("ShipAddress")
				_ShipAddress = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("ShipAddress")
				OnShipAddressChanged()
			End Set
		End Property
		Private _ShipAddress As Global.System.String
		Partial Private Sub OnShipAddressChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnShipAddressChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
		<DataMemberAttribute()>
		Public Property ShipCity() As Global.System.String
			Get
				Return _ShipCity
			End Get
			Set(ByVal value As System.String)
				OnShipCityChanging(value)
				ReportPropertyChanging("ShipCity")
				_ShipCity = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("ShipCity")
				OnShipCityChanged()
			End Set
		End Property
		Private _ShipCity As Global.System.String
		Partial Private Sub OnShipCityChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnShipCityChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
		<DataMemberAttribute()>
		Public Property ShipCountry() As Global.System.String
			Get
				Return _ShipCountry
			End Get
			Set(ByVal value As System.String)
				OnShipCountryChanging(value)
				ReportPropertyChanging("ShipCountry")
				_ShipCountry = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("ShipCountry")
				OnShipCountryChanged()
			End Set
		End Property
		Private _ShipCountry As Global.System.String
		Partial Private Sub OnShipCountryChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnShipCountryChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
		<DataMemberAttribute()>
		Public Property ShipName() As Global.System.String
			Get
				Return _ShipName
			End Get
			Set(ByVal value As System.String)
				OnShipNameChanging(value)
				ReportPropertyChanging("ShipName")
				_ShipName = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("ShipName")
				OnShipNameChanged()
			End Set
		End Property
		Private _ShipName As Global.System.String
		Partial Private Sub OnShipNameChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnShipNameChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
		<DataMemberAttribute()>
		Public Property ShippedDate() As Global.System.DateTime?
			Get
				Return _ShippedDate
			End Get
			Set(ByVal value? As DateTime)
				OnShippedDateChanging(value)
				ReportPropertyChanging("ShippedDate")
				_ShippedDate = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("ShippedDate")
				OnShippedDateChanged()
			End Set
		End Property
		Private _ShippedDate? As Global.System.DateTime
		Partial Private Sub OnShippedDateChanging(ByVal value? As Global.System.DateTime)
		End Sub
		Partial Private Sub OnShippedDateChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
		<DataMemberAttribute()>
		Public Property ShipPostalCode() As Global.System.String
			Get
				Return _ShipPostalCode
			End Get
			Set(ByVal value As System.String)
				OnShipPostalCodeChanging(value)
				ReportPropertyChanging("ShipPostalCode")
				_ShipPostalCode = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("ShipPostalCode")
				OnShipPostalCodeChanged()
			End Set
		End Property
		Private _ShipPostalCode As Global.System.String
		Partial Private Sub OnShipPostalCodeChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnShipPostalCodeChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
		<DataMemberAttribute()>
		Public Property ShipRegion() As Global.System.String
			Get
				Return _ShipRegion
			End Get
			Set(ByVal value As System.String)
				OnShipRegionChanging(value)
				ReportPropertyChanging("ShipRegion")
				_ShipRegion = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("ShipRegion")
				OnShipRegionChanged()
			End Set
		End Property
		Private _ShipRegion As Global.System.String
		Partial Private Sub OnShipRegionChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnShipRegionChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
		<DataMemberAttribute()>
		Public Property ShipVia() As Global.System.Int32?
			Get
				Return _ShipVia
			End Get
			Set(ByVal value? As System.Int32)
				OnShipViaChanging(value)
				ReportPropertyChanging("ShipVia")
				_ShipVia = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("ShipVia")
				OnShipViaChanged()
			End Set
		End Property
		Private _ShipVia? As Global.System.Int32
		Partial Private Sub OnShipViaChanging(ByVal value? As Global.System.Int32)
		End Sub
		Partial Private Sub OnShipViaChanged()
		End Sub

		#End Region


		#Region "Navigation Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<XmlIgnoreAttribute()>
		<SoapIgnoreAttribute()>
		<DataMemberAttribute()>
		<EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "FK_Orders_Customers", "Customers")>
		Public Property Customers() As Customers
			Get
				Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customers)("NorthwindModel.FK_Orders_Customers", "Customers").Value
			End Get
			Set(ByVal value As Customers)
				CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customers)("NorthwindModel.FK_Orders_Customers", "Customers").Value = value
			End Set
		End Property
		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<BrowsableAttribute(False)>
		<DataMemberAttribute()>
		Public Property CustomersReference() As EntityReference(Of Customers)
			Get
				Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customers)("NorthwindModel.FK_Orders_Customers", "Customers")
			End Get
			Set(ByVal value As EntityReference(Of Customers))
				If (value IsNot Nothing) Then
					CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Customers)("NorthwindModel.FK_Orders_Customers", "Customers", value)
				End If
			End Set
		End Property

		#End Region

	End Class

	#End Region


End Namespace
