
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("38ec042e-f8a0-4f08-bdf0-2760c65c4d95")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("NorthwindModel", "FK_Orders_Customers", "Customers", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(NorthwindModel.Customers), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(NorthwindModel.Orders))>

#End Region

Namespace NorthwindModel

    #Region "Contexts"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class NorthwindEntities
        Inherits ObjectContext
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new NorthwindEntities object using the connection string found in the 'NorthwindEntities' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=NorthwindEntities", "NorthwindEntities")
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new NorthwindEntities object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "NorthwindEntities")
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new NorthwindEntities object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "NorthwindEntities")
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Partial Methods"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "ObjectSet Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Customers() As ObjectSet(Of Customers)
            Get
                If (_Customers Is Nothing) Then
                    _Customers = MyBase.CreateObjectSet(Of Customers)("Customers")
                End If
                Return _Customers
            End Get
        End Property
    
        Private _Customers As ObjectSet(Of Customers)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Orders() As ObjectSet(Of Orders)
            Get
                If (_Orders Is Nothing) Then
                    _Orders = MyBase.CreateObjectSet(Of Orders)("Orders")
                End If
                Return _Orders
            End Get
        End Property
    
        Private _Orders As ObjectSet(Of Orders)

        #End Region

        #Region "AddTo Methods"
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToCustomers(ByVal customers As Customers)
            MyBase.AddObject("Customers", customers)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToOrders(ByVal orders As Orders)
            MyBase.AddObject("Orders", orders)
        End Sub

        #End Region

    End Class

    #End Region

    #Region "Entities"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="NorthwindModel", Name:="Customers")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Customers
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Customers object.
        ''' </summary>
        ''' <param name="companyName">Initial value of the CompanyName property.</param>
        ''' <param name="customerID">Initial value of the CustomerID property.</param>
        Public Shared Function CreateCustomers(companyName As Global.System.String, customerID As Global.System.String) As Customers
            Dim customers as Customers = New Customers
            customers.CompanyName = companyName
            customers.CustomerID = customerID
            Return customers
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Address() As Global.System.String
            Get
                Return _Address
            End Get
            Set
                OnAddressChanging(value)
                ReportPropertyChanging("Address")
                _Address = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Address")
                OnAddressChanged()
            End Set
        End Property
    
        Private _Address As Global.System.String
        Private Partial Sub OnAddressChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnAddressChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property City() As Global.System.String
            Get
                Return _City
            End Get
            Set
                OnCityChanging(value)
                ReportPropertyChanging("City")
                _City = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("City")
                OnCityChanged()
            End Set
        End Property
    
        Private _City As Global.System.String
        Private Partial Sub OnCityChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCityChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property CompanyName() As Global.System.String
            Get
                Return _CompanyName
            End Get
            Set
                OnCompanyNameChanging(value)
                ReportPropertyChanging("CompanyName")
                _CompanyName = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("CompanyName")
                OnCompanyNameChanged()
            End Set
        End Property
    
        Private _CompanyName As Global.System.String
        Private Partial Sub OnCompanyNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCompanyNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ContactName() As Global.System.String
            Get
                Return _ContactName
            End Get
            Set
                OnContactNameChanging(value)
                ReportPropertyChanging("ContactName")
                _ContactName = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("ContactName")
                OnContactNameChanged()
            End Set
        End Property
    
        Private _ContactName As Global.System.String
        Private Partial Sub OnContactNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnContactNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ContactTitle() As Global.System.String
            Get
                Return _ContactTitle
            End Get
            Set
                OnContactTitleChanging(value)
                ReportPropertyChanging("ContactTitle")
                _ContactTitle = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("ContactTitle")
                OnContactTitleChanged()
            End Set
        End Property
    
        Private _ContactTitle As Global.System.String
        Private Partial Sub OnContactTitleChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnContactTitleChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Country() As Global.System.String
            Get
                Return _Country
            End Get
            Set
                OnCountryChanging(value)
                ReportPropertyChanging("Country")
                _Country = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Country")
                OnCountryChanged()
            End Set
        End Property
    
        Private _Country As Global.System.String
        Private Partial Sub OnCountryChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCountryChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property CustomerID() As Global.System.String
            Get
                Return _CustomerID
            End Get
            Set
                If (_CustomerID <> Value) Then
                    OnCustomerIDChanging(value)
                    ReportPropertyChanging("CustomerID")
                    _CustomerID = StructuralObject.SetValidValue(value, false)
                    ReportPropertyChanged("CustomerID")
                    OnCustomerIDChanged()
                End If
            End Set
        End Property
    
        Private _CustomerID As Global.System.String
        Private Partial Sub OnCustomerIDChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCustomerIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Fax() As Global.System.String
            Get
                Return _Fax
            End Get
            Set
                OnFaxChanging(value)
                ReportPropertyChanging("Fax")
                _Fax = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Fax")
                OnFaxChanged()
            End Set
        End Property
    
        Private _Fax As Global.System.String
        Private Partial Sub OnFaxChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnFaxChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Phone() As Global.System.String
            Get
                Return _Phone
            End Get
            Set
                OnPhoneChanging(value)
                ReportPropertyChanging("Phone")
                _Phone = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Phone")
                OnPhoneChanged()
            End Set
        End Property
    
        Private _Phone As Global.System.String
        Private Partial Sub OnPhoneChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnPhoneChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property PostalCode() As Global.System.String
            Get
                Return _PostalCode
            End Get
            Set
                OnPostalCodeChanging(value)
                ReportPropertyChanging("PostalCode")
                _PostalCode = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("PostalCode")
                OnPostalCodeChanged()
            End Set
        End Property
    
        Private _PostalCode As Global.System.String
        Private Partial Sub OnPostalCodeChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnPostalCodeChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Region() As Global.System.String
            Get
                Return _Region
            End Get
            Set
                OnRegionChanging(value)
                ReportPropertyChanging("Region")
                _Region = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Region")
                OnRegionChanged()
            End Set
        End Property
    
        Private _Region As Global.System.String
        Private Partial Sub OnRegionChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnRegionChanged()
        End Sub

        #End Region

        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "FK_Orders_Customers", "Orders")>
         Public Property Orders() As EntityCollection(Of Orders)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Orders)("NorthwindModel.FK_Orders_Customers", "Orders")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Orders)("NorthwindModel.FK_Orders_Customers", "Orders", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="NorthwindModel", Name:="Orders")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Orders
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Orders object.
        ''' </summary>
        ''' <param name="orderID">Initial value of the OrderID property.</param>
        Public Shared Function CreateOrders(orderID As Global.System.Int32) As Orders
            Dim orders as Orders = New Orders
            orders.OrderID = orderID
            Return orders
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property EmployeeID() As Nullable(Of Global.System.Int32)
            Get
                Return _EmployeeID
            End Get
            Set
                OnEmployeeIDChanging(value)
                ReportPropertyChanging("EmployeeID")
                _EmployeeID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("EmployeeID")
                OnEmployeeIDChanged()
            End Set
        End Property
    
        Private _EmployeeID As Nullable(Of Global.System.Int32)
        Private Partial Sub OnEmployeeIDChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnEmployeeIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Freight() As Nullable(Of Global.System.Decimal)
            Get
                Return _Freight
            End Get
            Set
                OnFreightChanging(value)
                ReportPropertyChanging("Freight")
                _Freight = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Freight")
                OnFreightChanged()
            End Set
        End Property
    
        Private _Freight As Nullable(Of Global.System.Decimal)
        Private Partial Sub OnFreightChanging(value As Nullable(Of Global.System.Decimal))
        End Sub
    
        Private Partial Sub OnFreightChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property OrderDate() As Nullable(Of Global.System.DateTime)
            Get
                Return _OrderDate
            End Get
            Set
                OnOrderDateChanging(value)
                ReportPropertyChanging("OrderDate")
                _OrderDate = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("OrderDate")
                OnOrderDateChanged()
            End Set
        End Property
    
        Private _OrderDate As Nullable(Of Global.System.DateTime)
        Private Partial Sub OnOrderDateChanging(value As Nullable(Of Global.System.DateTime))
        End Sub
    
        Private Partial Sub OnOrderDateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrderID() As Global.System.Int32
            Get
                Return _OrderID
            End Get
            Set
                If (_OrderID <> Value) Then
                    OnOrderIDChanging(value)
                    ReportPropertyChanging("OrderID")
                    _OrderID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("OrderID")
                    OnOrderIDChanged()
                End If
            End Set
        End Property
    
        Private _OrderID As Global.System.Int32
        Private Partial Sub OnOrderIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnOrderIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property RequiredDate() As Nullable(Of Global.System.DateTime)
            Get
                Return _RequiredDate
            End Get
            Set
                OnRequiredDateChanging(value)
                ReportPropertyChanging("RequiredDate")
                _RequiredDate = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("RequiredDate")
                OnRequiredDateChanged()
            End Set
        End Property
    
        Private _RequiredDate As Nullable(Of Global.System.DateTime)
        Private Partial Sub OnRequiredDateChanging(value As Nullable(Of Global.System.DateTime))
        End Sub
    
        Private Partial Sub OnRequiredDateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ShipAddress() As Global.System.String
            Get
                Return _ShipAddress
            End Get
            Set
                OnShipAddressChanging(value)
                ReportPropertyChanging("ShipAddress")
                _ShipAddress = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("ShipAddress")
                OnShipAddressChanged()
            End Set
        End Property
    
        Private _ShipAddress As Global.System.String
        Private Partial Sub OnShipAddressChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnShipAddressChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ShipCity() As Global.System.String
            Get
                Return _ShipCity
            End Get
            Set
                OnShipCityChanging(value)
                ReportPropertyChanging("ShipCity")
                _ShipCity = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("ShipCity")
                OnShipCityChanged()
            End Set
        End Property
    
        Private _ShipCity As Global.System.String
        Private Partial Sub OnShipCityChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnShipCityChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ShipCountry() As Global.System.String
            Get
                Return _ShipCountry
            End Get
            Set
                OnShipCountryChanging(value)
                ReportPropertyChanging("ShipCountry")
                _ShipCountry = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("ShipCountry")
                OnShipCountryChanged()
            End Set
        End Property
    
        Private _ShipCountry As Global.System.String
        Private Partial Sub OnShipCountryChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnShipCountryChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ShipName() As Global.System.String
            Get
                Return _ShipName
            End Get
            Set
                OnShipNameChanging(value)
                ReportPropertyChanging("ShipName")
                _ShipName = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("ShipName")
                OnShipNameChanged()
            End Set
        End Property
    
        Private _ShipName As Global.System.String
        Private Partial Sub OnShipNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnShipNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ShippedDate() As Nullable(Of Global.System.DateTime)
            Get
                Return _ShippedDate
            End Get
            Set
                OnShippedDateChanging(value)
                ReportPropertyChanging("ShippedDate")
                _ShippedDate = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ShippedDate")
                OnShippedDateChanged()
            End Set
        End Property
    
        Private _ShippedDate As Nullable(Of Global.System.DateTime)
        Private Partial Sub OnShippedDateChanging(value As Nullable(Of Global.System.DateTime))
        End Sub
    
        Private Partial Sub OnShippedDateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ShipPostalCode() As Global.System.String
            Get
                Return _ShipPostalCode
            End Get
            Set
                OnShipPostalCodeChanging(value)
                ReportPropertyChanging("ShipPostalCode")
                _ShipPostalCode = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("ShipPostalCode")
                OnShipPostalCodeChanged()
            End Set
        End Property
    
        Private _ShipPostalCode As Global.System.String
        Private Partial Sub OnShipPostalCodeChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnShipPostalCodeChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ShipRegion() As Global.System.String
            Get
                Return _ShipRegion
            End Get
            Set
                OnShipRegionChanging(value)
                ReportPropertyChanging("ShipRegion")
                _ShipRegion = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("ShipRegion")
                OnShipRegionChanged()
            End Set
        End Property
    
        Private _ShipRegion As Global.System.String
        Private Partial Sub OnShipRegionChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnShipRegionChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ShipVia() As Nullable(Of Global.System.Int32)
            Get
                Return _ShipVia
            End Get
            Set
                OnShipViaChanging(value)
                ReportPropertyChanging("ShipVia")
                _ShipVia = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ShipVia")
                OnShipViaChanged()
            End Set
        End Property
    
        Private _ShipVia As Nullable(Of Global.System.Int32)
        Private Partial Sub OnShipViaChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnShipViaChanged()
        End Sub

        #End Region

        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "FK_Orders_Customers", "Customers")>
        Public Property Customers() As Customers
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customers)("NorthwindModel.FK_Orders_Customers", "Customers").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customers)("NorthwindModel.FK_Orders_Customers", "Customers").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property CustomersReference() As EntityReference(Of Customers)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customers)("NorthwindModel.FK_Orders_Customers", "Customers")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Customers)("NorthwindModel.FK_Orders_Customers", "Customers", value)
                End If
            End Set
        End Property

        #End Region

    End Class

    #End Region

    
End Namespace
