'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute()>
<Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("NorthwindModel", "FK_Orders_Customers", "Customers", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Entities.Customers), "Orders", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Entities.Orders))>

' Original file name:
' Generation date: 8/22/2008 9:51:55 AM
Namespace Entities

	''' <summary>
	''' There are no comments for NorthwindEntities in the schema.
	''' </summary>
	Partial Public Class NorthwindEntities
		Inherits System.Data.Objects.ObjectContext
		''' <summary>
		''' Initializes a new NorthwindEntities object using the connection string found in the 'NorthwindEntities' section of the application configuration file.
		''' </summary>
		Public Sub New()
			MyBase.New("name=NorthwindEntities", "NorthwindEntities")
			Me.OnContextCreated()
		End Sub
		''' <summary>
		''' Initialize a new NorthwindEntities object.
		''' </summary>
		Public Sub New(ByVal connectionString As String)
			MyBase.New(connectionString, "NorthwindEntities")
			Me.OnContextCreated()
		End Sub
		''' <summary>
		''' Initialize a new NorthwindEntities object.
		''' </summary>
		Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
			MyBase.New(connection, "NorthwindEntities")
			Me.OnContextCreated()
		End Sub
		Partial Private Sub OnContextCreated()
		End Sub
		''' <summary>
		''' There are no comments for Customers in the schema.
		''' </summary>
		Public ReadOnly Property Customers() As Global.System.Data.Objects.ObjectQuery(Of Customers)
			Get
				If (Me._Customers Is Nothing) Then
					Me._Customers = MyBase.CreateQuery(Of Customers)("[Customers]")
				End If
				Return Me._Customers
			End Get
		End Property
		Private _Customers As Global.System.Data.Objects.ObjectQuery(Of Customers)
		''' <summary>
		''' There are no comments for Orders in the schema.
		''' </summary>
		Public ReadOnly Property Orders() As Global.System.Data.Objects.ObjectQuery(Of Orders)
			Get
				If (Me._Orders Is Nothing) Then
					Me._Orders = MyBase.CreateQuery(Of Orders)("[Orders]")
				End If
				Return Me._Orders
			End Get
		End Property
		Private _Orders As Global.System.Data.Objects.ObjectQuery(Of Orders)
		''' <summary>
		''' There are no comments for Customers in the schema.
		''' </summary>
		Public Sub AddToCustomers(ByVal customers As Customers)
			MyBase.AddObject("Customers", customers)
		End Sub
		''' <summary>
		''' There are no comments for Orders in the schema.
		''' </summary>
		Public Sub AddToOrders(ByVal orders As Orders)
			MyBase.AddObject("Orders", orders)
		End Sub
	End Class
	''' <summary>
	''' There are no comments for NorthwindModel.Customers in the schema.
	''' </summary>
	''' <KeyProperties>
	''' CustomerID
	''' </KeyProperties>
	<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="NorthwindModel", Name:="Customers"), Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=True), Global.System.Serializable()> _
	Partial Public Class Customers
		Inherits System.Data.Objects.DataClasses.EntityObject
		''' <summary>
		''' Create a new Customers object.
		''' </summary>
		''' <param name="companyName">Initial value of CompanyName.</param>
		''' <param name="customerID">Initial value of CustomerID.</param>
		Public Shared Function CreateCustomers(ByVal companyName As String, ByVal customerID As String) As Customers
			Dim customers As New Customers()
			customers.CompanyName = companyName
			customers.CustomerID = customerID
			Return customers
		End Function
		''' <summary>
		''' There are no comments for Property Address in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property Address() As String
			Get
				Return Me._Address
			End Get
			Set(ByVal value As String)
				Me.OnAddressChanging(value)
				Me.ReportPropertyChanging("Address")
				Me._Address = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("Address")
				Me.OnAddressChanged()
			End Set
		End Property
		Private _Address As String
		Partial Private Sub OnAddressChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnAddressChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property City in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property City() As String
			Get
				Return Me._City
			End Get
			Set(ByVal value As String)
				Me.OnCityChanging(value)
				Me.ReportPropertyChanging("City")
				Me._City = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("City")
				Me.OnCityChanged()
			End Set
		End Property
		Private _City As String
		Partial Private Sub OnCityChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnCityChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property CompanyName in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=False), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property CompanyName() As String
			Get
				Return Me._CompanyName
			End Get
			Set(ByVal value As String)
				Me.OnCompanyNameChanging(value)
				Me.ReportPropertyChanging("CompanyName")
				Me._CompanyName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, False)
				Me.ReportPropertyChanged("CompanyName")
				Me.OnCompanyNameChanged()
			End Set
		End Property
		Private _CompanyName As String
		Partial Private Sub OnCompanyNameChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnCompanyNameChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ContactName in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property ContactName() As String
			Get
				Return Me._ContactName
			End Get
			Set(ByVal value As String)
				Me.OnContactNameChanging(value)
				Me.ReportPropertyChanging("ContactName")
				Me._ContactName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("ContactName")
				Me.OnContactNameChanged()
			End Set
		End Property
		Private _ContactName As String
		Partial Private Sub OnContactNameChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnContactNameChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ContactTitle in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property ContactTitle() As String
			Get
				Return Me._ContactTitle
			End Get
			Set(ByVal value As String)
				Me.OnContactTitleChanging(value)
				Me.ReportPropertyChanging("ContactTitle")
				Me._ContactTitle = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("ContactTitle")
				Me.OnContactTitleChanged()
			End Set
		End Property
		Private _ContactTitle As String
		Partial Private Sub OnContactTitleChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnContactTitleChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Country in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property Country() As String
			Get
				Return Me._Country
			End Get
			Set(ByVal value As String)
				Me.OnCountryChanging(value)
				Me.ReportPropertyChanging("Country")
				Me._Country = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("Country")
				Me.OnCountryChanged()
			End Set
		End Property
		Private _Country As String
		Partial Private Sub OnCountryChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnCountryChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property CustomerID in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property CustomerID() As String
			Get
				Return Me._CustomerID
			End Get
			Set(ByVal value As String)
				Me.OnCustomerIDChanging(value)
				Me.ReportPropertyChanging("CustomerID")
				Me._CustomerID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, False)
				Me.ReportPropertyChanged("CustomerID")
				Me.OnCustomerIDChanged()
			End Set
		End Property
		Private _CustomerID As String
		Partial Private Sub OnCustomerIDChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnCustomerIDChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Fax in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property Fax() As String
			Get
				Return Me._Fax
			End Get
			Set(ByVal value As String)
				Me.OnFaxChanging(value)
				Me.ReportPropertyChanging("Fax")
				Me._Fax = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("Fax")
				Me.OnFaxChanged()
			End Set
		End Property
		Private _Fax As String
		Partial Private Sub OnFaxChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnFaxChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Phone in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property Phone() As String
			Get
				Return Me._Phone
			End Get
			Set(ByVal value As String)
				Me.OnPhoneChanging(value)
				Me.ReportPropertyChanging("Phone")
				Me._Phone = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("Phone")
				Me.OnPhoneChanged()
			End Set
		End Property
		Private _Phone As String
		Partial Private Sub OnPhoneChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnPhoneChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property PostalCode in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property PostalCode() As String
			Get
				Return Me._PostalCode
			End Get
			Set(ByVal value As String)
				Me.OnPostalCodeChanging(value)
				Me.ReportPropertyChanging("PostalCode")
				Me._PostalCode = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("PostalCode")
				Me.OnPostalCodeChanged()
			End Set
		End Property
		Private _PostalCode As String
		Partial Private Sub OnPostalCodeChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnPostalCodeChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Region in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property Region() As String
			Get
				Return Me._Region
			End Get
			Set(ByVal value As String)
				Me.OnRegionChanging(value)
				Me.ReportPropertyChanging("Region")
				Me._Region = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("Region")
				Me.OnRegionChanged()
			End Set
		End Property
		Private _Region As String
		Partial Private Sub OnRegionChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnRegionChanged()
		End Sub
		''' <summary>
		''' There are no comments for Orders in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "FK_Orders_Customers", "Orders"), Global.System.Xml.Serialization.XmlIgnoreAttribute(), Global.System.Xml.Serialization.SoapIgnoreAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property Orders() As Global.System.Data.Objects.DataClasses.EntityCollection(Of Orders)
			Get
				Return (CType(Me, Global.System.Data.Objects.DataClasses.IEntityWithRelationships)).RelationshipManager.GetRelatedCollection(Of Orders)("NorthwindModel.FK_Orders_Customers", "Orders")
			End Get
			Set(ByVal value As System.Data.Objects.DataClasses.EntityCollection(Of Orders))
				If (value IsNot Nothing) Then
					CType(Me, Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Orders)("NorthwindModel.FK_Orders_Customers", "Orders", value)
				End If
			End Set
		End Property
	End Class
	''' <summary>
	''' There are no comments for NorthwindModel.Orders in the schema.
	''' </summary>
	''' <KeyProperties>
	''' OrderID
	''' </KeyProperties>
	<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="NorthwindModel", Name:="Orders"), Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=True), Global.System.Serializable()> _
	Partial Public Class Orders
		Inherits System.Data.Objects.DataClasses.EntityObject
		''' <summary>
		''' Create a new Orders object.
		''' </summary>
		''' <param name="orderID">Initial value of OrderID.</param>
		Public Shared Function CreateOrders(ByVal orderID As Integer) As Orders
			Dim orders As New Orders()
			orders.OrderID = orderID
			Return orders
		End Function
		''' <summary>
		''' There are no comments for Property EmployeeID in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property EmployeeID() As Integer?
			Get
				Return Me._EmployeeID
			End Get
			Set(ByVal value? As Integer)
				Me.OnEmployeeIDChanging(value)
				Me.ReportPropertyChanging("EmployeeID")
				Me._EmployeeID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
				Me.ReportPropertyChanged("EmployeeID")
				Me.OnEmployeeIDChanged()
			End Set
		End Property
		Private _EmployeeID? As Integer
		Partial Private Sub OnEmployeeIDChanging(ByVal value? As Integer)
		End Sub
		Partial Private Sub OnEmployeeIDChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Freight in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property Freight() As Decimal?
			Get
				Return Me._Freight
			End Get
			Set(ByVal value? As Decimal)
				Me.OnFreightChanging(value)
				Me.ReportPropertyChanging("Freight")
				Me._Freight = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
				Me.ReportPropertyChanged("Freight")
				Me.OnFreightChanged()
			End Set
		End Property
		Private _Freight? As Decimal
		Partial Private Sub OnFreightChanging(ByVal value? As Decimal)
		End Sub
		Partial Private Sub OnFreightChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property OrderDate in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property OrderDate() As Global.System.DateTime?
			Get
				Return Me._OrderDate
			End Get
			Set(ByVal value? As System.DateTime)
				Me.OnOrderDateChanging(value)
				Me.ReportPropertyChanging("OrderDate")
				Me._OrderDate = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
				Me.ReportPropertyChanged("OrderDate")
				Me.OnOrderDateChanged()
			End Set
		End Property
		Private _OrderDate? As Global.System.DateTime
		Partial Private Sub OnOrderDateChanging(ByVal value? As Global.System.DateTime)
		End Sub
		Partial Private Sub OnOrderDateChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property OrderID in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property OrderID() As Integer
			Get
				Return Me._OrderID
			End Get
			Set(ByVal value As Integer)
				Me.OnOrderIDChanging(value)
				Me.ReportPropertyChanging("OrderID")
				Me._OrderID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
				Me.ReportPropertyChanged("OrderID")
				Me.OnOrderIDChanged()
			End Set
		End Property
		Private _OrderID As Integer
		Partial Private Sub OnOrderIDChanging(ByVal value As Integer)
		End Sub
		Partial Private Sub OnOrderIDChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property RequiredDate in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property RequiredDate() As Global.System.DateTime?
			Get
				Return Me._RequiredDate
			End Get
			Set(ByVal value? As System.DateTime)
				Me.OnRequiredDateChanging(value)
				Me.ReportPropertyChanging("RequiredDate")
				Me._RequiredDate = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
				Me.ReportPropertyChanged("RequiredDate")
				Me.OnRequiredDateChanged()
			End Set
		End Property
		Private _RequiredDate? As Global.System.DateTime
		Partial Private Sub OnRequiredDateChanging(ByVal value? As Global.System.DateTime)
		End Sub
		Partial Private Sub OnRequiredDateChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ShipAddress in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property ShipAddress() As String
			Get
				Return Me._ShipAddress
			End Get
			Set(ByVal value As String)
				Me.OnShipAddressChanging(value)
				Me.ReportPropertyChanging("ShipAddress")
				Me._ShipAddress = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("ShipAddress")
				Me.OnShipAddressChanged()
			End Set
		End Property
		Private _ShipAddress As String
		Partial Private Sub OnShipAddressChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnShipAddressChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ShipCity in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property ShipCity() As String
			Get
				Return Me._ShipCity
			End Get
			Set(ByVal value As String)
				Me.OnShipCityChanging(value)
				Me.ReportPropertyChanging("ShipCity")
				Me._ShipCity = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("ShipCity")
				Me.OnShipCityChanged()
			End Set
		End Property
		Private _ShipCity As String
		Partial Private Sub OnShipCityChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnShipCityChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ShipCountry in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property ShipCountry() As String
			Get
				Return Me._ShipCountry
			End Get
			Set(ByVal value As String)
				Me.OnShipCountryChanging(value)
				Me.ReportPropertyChanging("ShipCountry")
				Me._ShipCountry = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("ShipCountry")
				Me.OnShipCountryChanged()
			End Set
		End Property
		Private _ShipCountry As String
		Partial Private Sub OnShipCountryChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnShipCountryChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ShipName in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property ShipName() As String
			Get
				Return Me._ShipName
			End Get
			Set(ByVal value As String)
				Me.OnShipNameChanging(value)
				Me.ReportPropertyChanging("ShipName")
				Me._ShipName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("ShipName")
				Me.OnShipNameChanged()
			End Set
		End Property
		Private _ShipName As String
		Partial Private Sub OnShipNameChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnShipNameChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ShippedDate in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property ShippedDate() As Global.System.DateTime?
			Get
				Return Me._ShippedDate
			End Get
			Set(ByVal value? As System.DateTime)
				Me.OnShippedDateChanging(value)
				Me.ReportPropertyChanging("ShippedDate")
				Me._ShippedDate = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
				Me.ReportPropertyChanged("ShippedDate")
				Me.OnShippedDateChanged()
			End Set
		End Property
		Private _ShippedDate? As Global.System.DateTime
		Partial Private Sub OnShippedDateChanging(ByVal value? As Global.System.DateTime)
		End Sub
		Partial Private Sub OnShippedDateChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ShipPostalCode in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property ShipPostalCode() As String
			Get
				Return Me._ShipPostalCode
			End Get
			Set(ByVal value As String)
				Me.OnShipPostalCodeChanging(value)
				Me.ReportPropertyChanging("ShipPostalCode")
				Me._ShipPostalCode = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("ShipPostalCode")
				Me.OnShipPostalCodeChanged()
			End Set
		End Property
		Private _ShipPostalCode As String
		Partial Private Sub OnShipPostalCodeChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnShipPostalCodeChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ShipRegion in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property ShipRegion() As String
			Get
				Return Me._ShipRegion
			End Get
			Set(ByVal value As String)
				Me.OnShipRegionChanging(value)
				Me.ReportPropertyChanging("ShipRegion")
				Me._ShipRegion = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("ShipRegion")
				Me.OnShipRegionChanged()
			End Set
		End Property
		Private _ShipRegion As String
		Partial Private Sub OnShipRegionChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnShipRegionChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ShipVia in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property ShipVia() As Integer?
			Get
				Return Me._ShipVia
			End Get
			Set(ByVal value? As Integer)
				Me.OnShipViaChanging(value)
				Me.ReportPropertyChanging("ShipVia")
				Me._ShipVia = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
				Me.ReportPropertyChanged("ShipVia")
				Me.OnShipViaChanged()
			End Set
		End Property
		Private _ShipVia? As Integer
		Partial Private Sub OnShipViaChanging(ByVal value? As Integer)
		End Sub
		Partial Private Sub OnShipViaChanged()
		End Sub
		''' <summary>
		''' There are no comments for Customers in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "FK_Orders_Customers", "Customers"), Global.System.Xml.Serialization.XmlIgnoreAttribute(), Global.System.Xml.Serialization.SoapIgnoreAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property Customers() As Customers
			Get
				Return (CType(Me, Global.System.Data.Objects.DataClasses.IEntityWithRelationships)).RelationshipManager.GetRelatedReference(Of Customers)("NorthwindModel.FK_Orders_Customers", "Customers").Value
			End Get
			Set(ByVal value As Customers)
				CType(Me, Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customers)("NorthwindModel.FK_Orders_Customers", "Customers").Value = value
			End Set
		End Property
		''' <summary>
		''' There are no comments for Customers in the schema.
		''' </summary>
		<Global.System.ComponentModel.BrowsableAttribute(False), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property CustomersReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Customers)
			Get
				Return (CType(Me, Global.System.Data.Objects.DataClasses.IEntityWithRelationships)).RelationshipManager.GetRelatedReference(Of Customers)("NorthwindModel.FK_Orders_Customers", "Customers")
			End Get
			Set(ByVal value As System.Data.Objects.DataClasses.EntityReference(Of Customers))
				If (value IsNot Nothing) Then
					CType(Me, Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Customers)("NorthwindModel.FK_Orders_Customers", "Customers", value)
				End If
			End Set
		End Property
	End Class
End Namespace
